#!/usr/bin/env python3
"""Render actual perspective motion and angle-dependent holographic light.

The vector front is the design master. This renderer operates on its raster
export; it does not fake movement with a glow around a stationary image.
Animation is built once for an edition, not regenerated by the daily data job.
"""
from __future__ import annotations
import colorsys
import json
import math
import sys
from pathlib import Path
from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT=Path(__file__).resolve().parents[1]
DEST=ROOT/'assets/holo'
SIZE=(720,740)
FRAMES=96
DURATION=80


def solve(matrix,values):
    """Small pivoted Gaussian elimination, avoiding a NumPy dependency."""
    a=[list(map(float,row))+[float(value)] for row,value in zip(matrix,values)]
    n=len(a)
    for i in range(n):
        pivot=max(range(i,n),key=lambda j:abs(a[j][i]))
        a[i],a[pivot]=a[pivot],a[i]
        if abs(a[i][i])<1e-12: raise ValueError('Singular perspective matrix')
        factor=a[i][i]
        a[i]=[v/factor for v in a[i]]
        for j in range(n):
            if j!=i:
                factor=a[j][i]
                a[j]=[v-factor*p for v,p in zip(a[j],a[i])]
    return [row[-1] for row in a]


def inverse_homography(source,target):
    matrix=[];values=[]
    for (u,v),(x,y) in zip(source,target):
        matrix += [[x,y,1,0,0,0,-u*x,-u*y],[0,0,0,x,y,1,-v*x,-v*y]]
        values += [u,v]
    return solve(matrix,values)


def card_quad(phase):
    angle=math.tau*phase
    yaw=.29*math.sin(angle)
    pitch=.11*math.cos(angle)
    roll=.055*math.sin(angle+.65)
    corners=[]
    for x,y in [(-200,-280),(200,-280),(200,280),(-200,280)]:
        xp=x*math.cos(yaw); z=-x*math.sin(yaw)
        yp=y*math.cos(pitch)-z*math.sin(pitch)
        z=y*math.sin(pitch)+z*math.cos(pitch)
        xr=xp*math.cos(roll)-yp*math.sin(roll)
        yr=xp*math.sin(roll)+yp*math.cos(roll)
        perspective=940/(940+z)
        corners.append((360+xr*perspective,349+yr*perspective+10*math.sin(angle)))
    return corners


def rainbow_texture():
    texture=Image.new('RGB',(1400,1400))
    d=ImageDraw.Draw(texture)
    for x in range(1400):
        rgb=tuple(int(v*255) for v in colorsys.hsv_to_rgb((x/620)%1,.60,.87))
        d.line((x,0,x,1400),fill=rgb)
    return texture.rotate(32,resample=Image.Resampling.BICUBIC)


def light_texture():
    texture=Image.new('L',(1400,1400))
    d=ImageDraw.Draw(texture)
    for x in range(1400):
        v=int(255*math.exp(-((x-700)/92)**2))
        if v: d.line((x,0,x,1400),fill=v)
    return texture.rotate(32,resample=Image.Resampling.BICUBIC)


def build_masks(size):
    width,height=size
    foil=Image.new('L',size,28)
    d=ImageDraw.Draw(foil)
    d.rounded_rectangle((27,89,413,351),9,fill=118)
    d.rounded_rectangle((1,1,width-2,height-2),24,outline=180,width=8)
    glitter=Image.new('L',size)
    d=ImageDraw.Draw(glitter)
    for y in range(4,height,13):
        for x in range(4,width,13):
            r=1 if (x+y)%3 else 2
            d.line((x-r,y,x+r,y),fill=175)
            d.line((x,y-r,x,y+r),fill=175)
    return foil,glitter


def background():
    bg=Image.new('RGBA',SIZE)
    d=ImageDraw.Draw(bg)
    for y in range(SIZE[1]):
        d.line((0,y,SIZE[0],y),fill=(10,13+int(3*y/SIZE[1]),23+int(8*y/SIZE[1]),255))
    floor=Image.new('RGBA',SIZE)
    d=ImageDraw.Draw(floor)
    d.ellipse((163,641,557,695),fill=(76,54,155,58))
    floor=floor.filter(ImageFilter.GaussianBlur(22))
    bg.alpha_composite(floor)
    return bg


def render_frame(base,phase,rainbow,light,foil,glitter,bg):
    theta=math.tau*phase
    w,h=base.size
    x=440+int(235*math.sin(theta))
    y=330+int(95*math.cos(theta))
    spectral=rainbow.crop((x,y,x+w,y+h))
    beam=light.crop((x,y,x+w,y+h))
    # Metallic color follows surface orientation. Body text has a low foil mask;
    # the illustration and metal edge carry the strongest reflection.
    illumination=ImageChops.screen(beam,Image.new('L',base.size,78))
    foil_amount=ImageChops.multiply(foil,illumination)
    rgb=base.convert('RGB')
    rgb=Image.composite(ImageChops.screen(rgb,spectral),rgb,foil_amount)
    white_amount=ImageChops.multiply(beam,foil).point(lambda v:int(v*.80))
    rgb=Image.composite(ImageChops.screen(rgb,Image.new('RGB',base.size,'white')),rgb,white_amount)
    glints=ImageChops.multiply(glitter,beam).point(lambda v:int(v*.58))
    rgb=Image.composite(ImageChops.screen(rgb,Image.new('RGB',base.size,(206,224,255))),rgb,glints)
    face=rgb.convert('RGBA');face.putalpha(base.getchannel('A'))
    quad=card_quad(phase)
    transform=inverse_homography([(0,0),(w,0),(w,h),(0,h)],quad)
    warped=face.transform(SIZE,Image.Transform.PERSPECTIVE,transform,resample=Image.Resampling.BICUBIC)
    alpha=warped.getchannel('A')
    result=bg.copy()
    shadow=Image.new('RGBA',SIZE,(0,0,0,0))
    shadowalpha=alpha.filter(ImageFilter.GaussianBlur(20)).point(lambda v:int(v*.65))
    shadow.putalpha(shadowalpha)
    result.alpha_composite(shadow,dest=(0,13))
    hue=(.58+.14*math.sin(theta+.7))%1
    color=tuple(int(v*255) for v in colorsys.hsv_to_rgb(hue,.75,1))
    glow=Image.new('RGBA',SIZE,color+(0,))
    glow.putalpha(alpha.filter(ImageFilter.GaussianBlur(19)).point(lambda v:int(v*(.42+.14*math.cos(theta)))))
    result.alpha_composite(glow)
    # A second, tighter edge glow leaves the card silhouette visibly luminous.
    tight=Image.new('RGBA',SIZE,(133,191,255,0))
    tight.putalpha(alpha.filter(ImageFilter.GaussianBlur(5)).point(lambda v:int(v*.27)))
    result.alpha_composite(tight)
    result.alpha_composite(warped)
    return result.convert('RGB')


def make_animation():
    base=Image.open(DEST/'card-front.png').convert('RGBA')
    rainbow,light=rainbow_texture(),light_texture()
    foil,glitter=build_masks(base.size)
    bg=background()
    frames=[]
    for i in range(FRAMES):
        frames.append(render_frame(base,i/FRAMES,rainbow,light,foil,glitter,bg))
        if i%24==0: print(f'Perspective / foil frame {i+1}/{FRAMES}',flush=True)
    # Share one palette across all frames: steady color instead of palette flicker.
    samples=Image.new('RGB',(8*90,2*93))
    for j,i in enumerate(range(0,FRAMES,6)):
        sample=frames[i].resize((90,93),Image.Resampling.LANCZOS)
        samples.paste(sample,((j%8)*90,(j//8)*93))
    palette=samples.quantize(colors=256,method=Image.Quantize.MEDIANCUT)
    # The fallback is smaller; modern browsers receive the full-resolution WebP.
    fallback=[frame.resize((540,555),Image.Resampling.LANCZOS) for frame in frames[::2]]
    indexed=[frame.quantize(palette=palette,dither=Image.Dither.NONE) for frame in fallback]
    indexed[0].save(DEST/'profile.gif',save_all=True,append_images=indexed[1:],loop=0,
                    duration=DURATION*2,disposal=1,optimize=True)
    frames[0].save(DEST/'profile-still.png')
    frames[0].save(DEST/'profile.webp',save_all=True,append_images=frames[1:],loop=0,
                  duration=DURATION,quality=72,method=5,minimize_size=True)
    meta={'frames':FRAMES,'duration_ms':DURATION,'loop_ms':FRAMES*DURATION,
          'size':list(SIZE),'projection':'3D yaw/pitch/roll with inverse homography',
          'effects':['angle-dependent iridescence','specular light band','micro-glints','colored edge halo'],
          'live_data_in_animation':False,'gif_fallback':{'frames':FRAMES//2,'duration_ms':DURATION*2,'size':[540,555]}}
    (DEST/'animation.json').write_text(json.dumps(meta,indent=2)+'\n')
    for name in ['profile.gif','profile.webp','profile-still.png']:
        with Image.open(DEST/name) as im:
            print(name,im.size,'frames:',getattr(im,'n_frames',1),'bytes:',(DEST/name).stat().st_size)
    sheet=Image.new('RGB',(720*3,740))
    for j,i in enumerate([0,24,48]): sheet.paste(frames[i],(j*720,0))
    if '--preview' in sys.argv:
        preview=Path(sys.argv[sys.argv.index('--preview')+1])
        sheet.save(preview)


if __name__=='__main__':
    make_animation()
